### PR TITLE
Release preparation

### PR DESCRIPTION
**Pull request by frederike-ramin**

### CODE REVIEW

**Comment by hpibptlab** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [attributeConfig-template.js](https://github.com/bptlab/argos-frontend/blob/99ff07b5fb71d59347753ad73d6a6e3e63115437/src/config/attributeConfig/attributeConfig-template.js): Rename this file to "attributeConfig". [rule](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3317)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by hpibptlab** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [attributeConfig-template.js](https://github.com/bptlab/argos-frontend/blob/56df8eae7766d9ea65fbf7d7b0b5f861d00aab0c/src/config/attributeConfig/attributeConfig-template.js): Rename this file to "attributeConfig". [rule](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3317)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by hpibptlab** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [attributeConfig-template.js](https://github.com/bptlab/argos-frontend/blob/234b36b68084cb35ac5927742ece2ecf9608b08a/src/config/attributeConfig/attributeConfig-template.js): Rename this file to "attributeConfig". [rule](http://bpt-lab.org/sonarqube/coding_rules#rule_key=javascript%3AS3317)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Review by tommartensen — APPROVED** [review]
Good Job!

**Pull request merged**
